/**
*   *********************************
*   AUTHOR: GUNASEKAR JABBALA
*   EMAIL: gunasekar.ai.dev@gmail.com
*   *********************************
*/
/**
*   **************************************************************************************************
*   DDL - DROP - TABLE
*   **************************************************************************************************
*/
DROP TABLE IF EXISTS EMPLOYEE CASCADE; 
DROP TABLE IF EXISTS DEPARTMENT CASCADE;
DROP TABLE IF EXISTS ADDRESS CASCADE;
DROP TABLE IF EXISTS LOCATION CASCADE;
DROP TABLE IF EXISTS CITY CASCADE;
DROP TABLE IF EXISTS STATE CASCADE;
DROP TABLE IF EXISTS SALARY CASCADE;
DROP TABLE IF EXISTS JOB CASCADE;
DROP TABLE IF EXISTS EDUCATION_LEVEL CASCADE;
DROP TABLE IF EXISTS EMPLOYEE_HISTORY CASCADE;



/**
*   **************************************************************************************************
*   DDL - CREATE - TABLE
*   **************************************************************************************************
*/

CREATE TABLE EMPLOYEE (EMP_ID  VARCHAR(8) PRIMARY KEY, EMP_NM VARCHAR(60) NOT NULL, EMAIL VARCHAR(60), HIRE_DT DATE);
CREATE TABLE DEPARTMENT(ID SERIAL PRIMARY KEY, DEPARTMENT_NM   VARCHAR(60) NOT NULL);
CREATE TABLE ADDRESS(ID SERIAL PRIMARY KEY, ADDRESS VARCHAR(100), LOCATION VARCHAR(60), CITY VARCHAR(60), STATE VARCHAR(2));
CREATE TABLE EDUCATION_LEVEL(ID SERIAL PRIMARY KEY, EDUCATION_LVL VARCHAR(60));
CREATE TABLE JOB(ID SERIAL PRIMARY KEY,JOB_TITLE VARCHAR(100));
CREATE TABLE SALARY(ID SERIAL PRIMARY KEY, SALARY INT);
CREATE TABLE EMPLOYEE_HISTORY(EMP_ID VARCHAR(8),ADDRESS_ID INT, EDUCATION_ID INT,MANAGER_ID VARCHAR(8), JOB_ID INT, DEPARTMENT_ID INT, SALARY_ID INT,START_DT DATE, END_DT DATE);


