CREATE OR REPLACE VIEW HUMAN_READABLE_VIEW_WITH_ALL_ATTRIBUTES AS
SELECT 
	E.EMP_ID,
    E.EMP_NM,
    E.EMAIL,
    E.HIRE_DT,
    J.JOB_TITLE,
    S.SALARY,
    D.DEPARTMENT_NM,
    M.EMP_NM AS "Manager",
    EH.START_DT,
    EH.END_DT,
    A.LOCATION,
    A.ADDRESS,
    A.CITY,
    A.STATE,
    L.EDUCATION_LVL
FROM EMPLOYEE E
LEFT OUTER JOIN EMPLOYEE_HISTORY EH ON EH.EMP_ID = E.EMP_ID
LEFT OUTER JOIN JOB J ON J.ID = EH.JOB_ID
LEFT OUTER JOIN SALARY S ON S.ID = EH.SALARY_ID
LEFT OUTER JOIN DEPARTMENT D ON D.ID = EH.DEPARTMENT_ID
LEFT OUTER JOIN EMPLOYEE M ON M.EMP_ID = EH.MANAGER_ID
LEFT OUTER JOIN ADDRESS A ON A.ID = EH.ADDRESS_ID
LEFT OUTER JOIN EDUCATION_LEVEL L ON L.ID= EH.EDUCATION_ID;